version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=climaplus
      - POSTGRES_PASSWORD=climaplus123
      - POSTGRES_DB=climaplus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - climanet
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s 
      timeout: 5s 
      retries: 5  


  # Backend (Node.js + Express)
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - OPENWEATHER_API_KEY=54a07a88081d9660c4449034b1d9571e
      - DATABASE_URL=postgres://climaplus:climaplus123@db:5432/climaplus
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - climanet

  # Frontend (React)
  frontend:
    build: ./climaplus-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - climanet

# Red y volúmenes
networks:
  climanet:

volumes:
  postgres_data: